// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_identity.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SourceType are the predefined types of image source allowed
type IdentityImage_SourceType int32

const (
	IdentityImage_UNKNOWN_SOURCE_TYPE IdentityImage_SourceType = 0
	// RAW_PAYLOAD image byte data
	IdentityImage_RAW_PAYLOAD IdentityImage_SourceType = 1
	// ENS_AVATAR uses the ENS record's resolver get-text-data.avatar data
	// The `payload` field will be ignored if ENS_AVATAR is selected
	// The application will read and parse the ENS avatar data as image payload data, URLs will be ignored
	// The parent `ChatMessageIdentity` must have a valid `ens_name` set
	IdentityImage_ENS_AVATAR IdentityImage_SourceType = 2
)

var IdentityImage_SourceType_name = map[int32]string{
	0: "UNKNOWN_SOURCE_TYPE",
	1: "RAW_PAYLOAD",
	2: "ENS_AVATAR",
}

var IdentityImage_SourceType_value = map[string]int32{
	"UNKNOWN_SOURCE_TYPE": 0,
	"RAW_PAYLOAD":         1,
	"ENS_AVATAR":          2,
}

func (x IdentityImage_SourceType) String() string {
	return proto.EnumName(IdentityImage_SourceType_name, int32(x))
}

func (IdentityImage_SourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a652489000a5879, []int{1, 0}
}

// ChatIdentity represents the user defined identity associated with their public chat key
type ChatIdentity struct {
	// Lamport timestamp of the message
	Clock uint64 `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	// ens_name is the valid ENS name associated with the chat key
	EnsName string `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	// images is a string indexed mapping of images associated with an identity
	Images map[string]*IdentityImage `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// display name is the user set identity, valid only for organisations
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description is the user set description, valid only for organisations
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Color                string   `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatIdentity) Reset()         { *m = ChatIdentity{} }
func (m *ChatIdentity) String() string { return proto.CompactTextString(m) }
func (*ChatIdentity) ProtoMessage()    {}
func (*ChatIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a652489000a5879, []int{0}
}

func (m *ChatIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatIdentity.Unmarshal(m, b)
}
func (m *ChatIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatIdentity.Marshal(b, m, deterministic)
}
func (m *ChatIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatIdentity.Merge(m, src)
}
func (m *ChatIdentity) XXX_Size() int {
	return xxx_messageInfo_ChatIdentity.Size(m)
}
func (m *ChatIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_ChatIdentity proto.InternalMessageInfo

func (m *ChatIdentity) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *ChatIdentity) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *ChatIdentity) GetImages() map[string]*IdentityImage {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *ChatIdentity) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ChatIdentity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ChatIdentity) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

// ProfileImage represents data associated with a user's profile image
type IdentityImage struct {
	// payload is a context based payload for the profile image data,
	// context is determined by the `source_type`
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// source_type signals the image payload source
	SourceType IdentityImage_SourceType `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=protobuf.IdentityImage_SourceType" json:"source_type,omitempty"`
	// image_type signals the image type and method of parsing the payload
	ImageType ImageType `protobuf:"varint,3,opt,name=image_type,json=imageType,proto3,enum=protobuf.ImageType" json:"image_type,omitempty"`
	// encryption_keys is a list of encrypted keys that can be used to decrypted an encrypted payload
	EncryptionKeys       [][]byte `protobuf:"bytes,4,rep,name=encryption_keys,json=encryptionKeys,proto3" json:"encryption_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityImage) Reset()         { *m = IdentityImage{} }
func (m *IdentityImage) String() string { return proto.CompactTextString(m) }
func (*IdentityImage) ProtoMessage()    {}
func (*IdentityImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a652489000a5879, []int{1}
}

func (m *IdentityImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityImage.Unmarshal(m, b)
}
func (m *IdentityImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityImage.Marshal(b, m, deterministic)
}
func (m *IdentityImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityImage.Merge(m, src)
}
func (m *IdentityImage) XXX_Size() int {
	return xxx_messageInfo_IdentityImage.Size(m)
}
func (m *IdentityImage) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityImage.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityImage proto.InternalMessageInfo

func (m *IdentityImage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *IdentityImage) GetSourceType() IdentityImage_SourceType {
	if m != nil {
		return m.SourceType
	}
	return IdentityImage_UNKNOWN_SOURCE_TYPE
}

func (m *IdentityImage) GetImageType() ImageType {
	if m != nil {
		return m.ImageType
	}
	return ImageType_UNKNOWN_IMAGE_TYPE
}

func (m *IdentityImage) GetEncryptionKeys() [][]byte {
	if m != nil {
		return m.EncryptionKeys
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.IdentityImage_SourceType", IdentityImage_SourceType_name, IdentityImage_SourceType_value)
	proto.RegisterType((*ChatIdentity)(nil), "protobuf.ChatIdentity")
	proto.RegisterMapType((map[string]*IdentityImage)(nil), "protobuf.ChatIdentity.ImagesEntry")
	proto.RegisterType((*IdentityImage)(nil), "protobuf.IdentityImage")
}

func init() {
	proto.RegisterFile("chat_identity.proto", fileDescriptor_7a652489000a5879)
}

var fileDescriptor_7a652489000a5879 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x6e, 0xdb, 0x30,
	0x10, 0xc6, 0x2b, 0xc9, 0x76, 0xe2, 0xa3, 0xeb, 0x18, 0x74, 0x81, 0xa8, 0x99, 0x54, 0x2f, 0xf5,
	0x52, 0x0d, 0xee, 0x52, 0x64, 0x13, 0x5c, 0x17, 0x08, 0x52, 0xc8, 0x01, 0xed, 0x34, 0xc8, 0x44,
	0x30, 0x32, 0xdb, 0x08, 0x96, 0x49, 0x41, 0xa4, 0x0a, 0xf0, 0x39, 0xfa, 0x16, 0x7d, 0xca, 0x22,
	0xa4, 0x54, 0x29, 0x13, 0xef, 0xcf, 0x77, 0xbf, 0xfb, 0x78, 0x30, 0xcf, 0x9e, 0x99, 0xa6, 0xf9,
	0x81, 0x0b, 0x9d, 0x6b, 0x13, 0x97, 0x95, 0xd4, 0x12, 0x9f, 0xdb, 0xe7, 0xa9, 0xfe, 0x79, 0x85,
	0xb8, 0xa8, 0x4f, 0xca, 0x95, 0x17, 0x7f, 0x7d, 0x98, 0xac, 0x9f, 0x99, 0xbe, 0x69, 0xd4, 0xf8,
	0x1d, 0x0c, 0xb3, 0x42, 0x66, 0xc7, 0xd0, 0x8b, 0xbc, 0xe5, 0x80, 0xb8, 0x04, 0xbf, 0x87, 0x73,
	0x2e, 0x14, 0x15, 0xec, 0xc4, 0x43, 0x3f, 0xf2, 0x96, 0x63, 0x72, 0xc6, 0x85, 0x4a, 0xd9, 0x89,
	0xe3, 0x6b, 0x18, 0xe5, 0x27, 0xf6, 0x8b, 0xab, 0x30, 0x88, 0x82, 0x25, 0x5a, 0x2d, 0xe2, 0x76,
	0x53, 0xdc, 0x07, 0xc7, 0x37, 0x56, 0xb4, 0x11, 0xba, 0x32, 0xa4, 0x99, 0xc0, 0x1f, 0x60, 0x72,
	0xc8, 0x55, 0x59, 0x30, 0xe3, 0xd0, 0x03, 0x8b, 0x46, 0x4d, 0xcd, 0xe2, 0x23, 0x40, 0x07, 0xae,
	0xb2, 0x2a, 0x2f, 0x75, 0x2e, 0x45, 0x38, 0x6c, 0x14, 0x5d, 0xc9, 0x3a, 0x96, 0x85, 0xac, 0xc2,
	0x91, 0xed, 0xb9, 0xe4, 0x8a, 0x00, 0xea, 0x6d, 0xc4, 0x33, 0x08, 0x8e, 0xdc, 0xd8, 0x4f, 0x8d,
	0xc9, 0x4b, 0x88, 0x3f, 0xc1, 0xf0, 0x37, 0x2b, 0x6a, 0xf7, 0x1f, 0xb4, 0xba, 0xec, 0x6c, 0xb7,
	0x96, 0xed, 0x3c, 0x71, 0xaa, 0x6b, 0xff, 0x8b, 0xb7, 0xf8, 0xe3, 0xc3, 0xdb, 0x57, 0x4d, 0x1c,
	0xc2, 0x59, 0xc9, 0x4c, 0x21, 0xd9, 0xc1, 0xa2, 0x27, 0xa4, 0x4d, 0xf1, 0x1a, 0x90, 0x92, 0x75,
	0x95, 0x71, 0xaa, 0x4d, 0xe9, 0x96, 0x4c, 0xfb, 0xb7, 0x79, 0xc5, 0x89, 0x77, 0x56, 0xba, 0x37,
	0x25, 0x27, 0xa0, 0xfe, 0xc7, 0x78, 0x05, 0x60, 0x2f, 0xe5, 0x18, 0x81, 0x65, 0xcc, 0x7b, 0x8c,
	0x97, 0x9e, 0x1d, 0x1a, 0xe7, 0x6d, 0x88, 0x3f, 0xc2, 0x05, 0x17, 0x59, 0x65, 0xec, 0x71, 0xe8,
	0x91, 0x1b, 0x15, 0x0e, 0xa2, 0x60, 0x39, 0x21, 0xd3, 0xae, 0x7c, 0xcb, 0x8d, 0x5a, 0x7c, 0x03,
	0xe8, 0xd6, 0xe2, 0x4b, 0x98, 0xdf, 0xa7, 0xb7, 0xe9, 0xf6, 0x21, 0xa5, 0xbb, 0xed, 0x3d, 0x59,
	0x6f, 0xe8, 0xfe, 0xf1, 0x6e, 0x33, 0x7b, 0x83, 0x2f, 0x00, 0x91, 0xe4, 0x81, 0xde, 0x25, 0x8f,
	0xdf, 0xb7, 0xc9, 0xd7, 0x99, 0x87, 0xa7, 0x00, 0x9b, 0x74, 0x47, 0x93, 0x1f, 0xc9, 0x3e, 0x21,
	0x33, 0xff, 0x69, 0x64, 0xfd, 0x7c, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xf4, 0x29, 0xd6,
	0x77, 0x02, 0x00, 0x00,
}
