// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communities.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunityPermissions_Access int32

const (
	CommunityPermissions_UNKNOWN_ACCESS  CommunityPermissions_Access = 0
	CommunityPermissions_NO_MEMBERSHIP   CommunityPermissions_Access = 1
	CommunityPermissions_INVITATION_ONLY CommunityPermissions_Access = 2
	CommunityPermissions_ON_REQUEST      CommunityPermissions_Access = 3
)

var CommunityPermissions_Access_name = map[int32]string{
	0: "UNKNOWN_ACCESS",
	1: "NO_MEMBERSHIP",
	2: "INVITATION_ONLY",
	3: "ON_REQUEST",
}

var CommunityPermissions_Access_value = map[string]int32{
	"UNKNOWN_ACCESS":  0,
	"NO_MEMBERSHIP":   1,
	"INVITATION_ONLY": 2,
	"ON_REQUEST":      3,
}

func (x CommunityPermissions_Access) String() string {
	return proto.EnumName(CommunityPermissions_Access_name, int32(x))
}

func (CommunityPermissions_Access) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{2, 0}
}

type Grant struct {
	CommunityId          []byte   `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	MemberId             []byte   `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Clock                uint64   `protobuf:"varint,4,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grant) Reset()         { *m = Grant{} }
func (m *Grant) String() string { return proto.CompactTextString(m) }
func (*Grant) ProtoMessage()    {}
func (*Grant) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{0}
}

func (m *Grant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grant.Unmarshal(m, b)
}
func (m *Grant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grant.Marshal(b, m, deterministic)
}
func (m *Grant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grant.Merge(m, src)
}
func (m *Grant) XXX_Size() int {
	return xxx_messageInfo_Grant.Size(m)
}
func (m *Grant) XXX_DiscardUnknown() {
	xxx_messageInfo_Grant.DiscardUnknown(m)
}

var xxx_messageInfo_Grant proto.InternalMessageInfo

func (m *Grant) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

func (m *Grant) GetMemberId() []byte {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *Grant) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *Grant) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

type CommunityMember struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityMember) Reset()         { *m = CommunityMember{} }
func (m *CommunityMember) String() string { return proto.CompactTextString(m) }
func (*CommunityMember) ProtoMessage()    {}
func (*CommunityMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{1}
}

func (m *CommunityMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityMember.Unmarshal(m, b)
}
func (m *CommunityMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityMember.Marshal(b, m, deterministic)
}
func (m *CommunityMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityMember.Merge(m, src)
}
func (m *CommunityMember) XXX_Size() int {
	return xxx_messageInfo_CommunityMember.Size(m)
}
func (m *CommunityMember) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityMember.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityMember proto.InternalMessageInfo

type CommunityPermissions struct {
	EnsOnly bool `protobuf:"varint,1,opt,name=ens_only,json=ensOnly,proto3" json:"ens_only,omitempty"`
	// https://gitlab.matrix.org/matrix-org/olm/blob/master/docs/megolm.md is a candidate for the algorithm to be used in case we want to have private communityal chats, lighter than pairwise encryption using the DR, less secure, but more efficient for large number of participants
	Private              bool                        `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
	Access               CommunityPermissions_Access `protobuf:"varint,3,opt,name=access,proto3,enum=protobuf.CommunityPermissions_Access" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CommunityPermissions) Reset()         { *m = CommunityPermissions{} }
func (m *CommunityPermissions) String() string { return proto.CompactTextString(m) }
func (*CommunityPermissions) ProtoMessage()    {}
func (*CommunityPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{2}
}

func (m *CommunityPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityPermissions.Unmarshal(m, b)
}
func (m *CommunityPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityPermissions.Marshal(b, m, deterministic)
}
func (m *CommunityPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityPermissions.Merge(m, src)
}
func (m *CommunityPermissions) XXX_Size() int {
	return xxx_messageInfo_CommunityPermissions.Size(m)
}
func (m *CommunityPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityPermissions proto.InternalMessageInfo

func (m *CommunityPermissions) GetEnsOnly() bool {
	if m != nil {
		return m.EnsOnly
	}
	return false
}

func (m *CommunityPermissions) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *CommunityPermissions) GetAccess() CommunityPermissions_Access {
	if m != nil {
		return m.Access
	}
	return CommunityPermissions_UNKNOWN_ACCESS
}

type CommunityDescription struct {
	Clock                uint64                      `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Members              map[string]*CommunityMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Permissions          *CommunityPermissions       `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Identity             *ChatIdentity               `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	Chats                map[string]*CommunityChat   `protobuf:"bytes,6,rep,name=chats,proto3" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CommunityDescription) Reset()         { *m = CommunityDescription{} }
func (m *CommunityDescription) String() string { return proto.CompactTextString(m) }
func (*CommunityDescription) ProtoMessage()    {}
func (*CommunityDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{3}
}

func (m *CommunityDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityDescription.Unmarshal(m, b)
}
func (m *CommunityDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityDescription.Marshal(b, m, deterministic)
}
func (m *CommunityDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityDescription.Merge(m, src)
}
func (m *CommunityDescription) XXX_Size() int {
	return xxx_messageInfo_CommunityDescription.Size(m)
}
func (m *CommunityDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityDescription.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityDescription proto.InternalMessageInfo

func (m *CommunityDescription) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityDescription) GetMembers() map[string]*CommunityMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CommunityDescription) GetPermissions() *CommunityPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *CommunityDescription) GetIdentity() *ChatIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *CommunityDescription) GetChats() map[string]*CommunityChat {
	if m != nil {
		return m.Chats
	}
	return nil
}

type CommunityChat struct {
	Members              map[string]*CommunityMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Permissions          *CommunityPermissions       `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Identity             *ChatIdentity               `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CommunityChat) Reset()         { *m = CommunityChat{} }
func (m *CommunityChat) String() string { return proto.CompactTextString(m) }
func (*CommunityChat) ProtoMessage()    {}
func (*CommunityChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{4}
}

func (m *CommunityChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityChat.Unmarshal(m, b)
}
func (m *CommunityChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityChat.Marshal(b, m, deterministic)
}
func (m *CommunityChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityChat.Merge(m, src)
}
func (m *CommunityChat) XXX_Size() int {
	return xxx_messageInfo_CommunityChat.Size(m)
}
func (m *CommunityChat) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityChat.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityChat proto.InternalMessageInfo

func (m *CommunityChat) GetMembers() map[string]*CommunityMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CommunityChat) GetPermissions() *CommunityPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *CommunityChat) GetIdentity() *ChatIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

type CommunityInvitation struct {
	CommunityDescription []byte   `protobuf:"bytes,1,opt,name=community_description,json=communityDescription,proto3" json:"community_description,omitempty"`
	Grant                []byte   `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityInvitation) Reset()         { *m = CommunityInvitation{} }
func (m *CommunityInvitation) String() string { return proto.CompactTextString(m) }
func (*CommunityInvitation) ProtoMessage()    {}
func (*CommunityInvitation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{5}
}

func (m *CommunityInvitation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityInvitation.Unmarshal(m, b)
}
func (m *CommunityInvitation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityInvitation.Marshal(b, m, deterministic)
}
func (m *CommunityInvitation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityInvitation.Merge(m, src)
}
func (m *CommunityInvitation) XXX_Size() int {
	return xxx_messageInfo_CommunityInvitation.Size(m)
}
func (m *CommunityInvitation) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityInvitation.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityInvitation proto.InternalMessageInfo

func (m *CommunityInvitation) GetCommunityDescription() []byte {
	if m != nil {
		return m.CommunityDescription
	}
	return nil
}

func (m *CommunityInvitation) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *CommunityInvitation) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CommunityInvitation) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type CommunityRequestJoin struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	EnsName              string   `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CommunityId          []byte   `protobuf:"bytes,4,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityRequestJoin) Reset()         { *m = CommunityRequestJoin{} }
func (m *CommunityRequestJoin) String() string { return proto.CompactTextString(m) }
func (*CommunityRequestJoin) ProtoMessage()    {}
func (*CommunityRequestJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{6}
}

func (m *CommunityRequestJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityRequestJoin.Unmarshal(m, b)
}
func (m *CommunityRequestJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityRequestJoin.Marshal(b, m, deterministic)
}
func (m *CommunityRequestJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityRequestJoin.Merge(m, src)
}
func (m *CommunityRequestJoin) XXX_Size() int {
	return xxx_messageInfo_CommunityRequestJoin.Size(m)
}
func (m *CommunityRequestJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityRequestJoin.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityRequestJoin proto.InternalMessageInfo

func (m *CommunityRequestJoin) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityRequestJoin) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *CommunityRequestJoin) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CommunityRequestJoin) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

type CommunityRequestJoinResponse struct {
	Clock                uint64                `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Community            *CommunityDescription `protobuf:"bytes,2,opt,name=community,proto3" json:"community,omitempty"`
	Accepted             bool                  `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Grant                []byte                `protobuf:"bytes,4,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CommunityRequestJoinResponse) Reset()         { *m = CommunityRequestJoinResponse{} }
func (m *CommunityRequestJoinResponse) String() string { return proto.CompactTextString(m) }
func (*CommunityRequestJoinResponse) ProtoMessage()    {}
func (*CommunityRequestJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{7}
}

func (m *CommunityRequestJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityRequestJoinResponse.Unmarshal(m, b)
}
func (m *CommunityRequestJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityRequestJoinResponse.Marshal(b, m, deterministic)
}
func (m *CommunityRequestJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityRequestJoinResponse.Merge(m, src)
}
func (m *CommunityRequestJoinResponse) XXX_Size() int {
	return xxx_messageInfo_CommunityRequestJoinResponse.Size(m)
}
func (m *CommunityRequestJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityRequestJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityRequestJoinResponse proto.InternalMessageInfo

func (m *CommunityRequestJoinResponse) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityRequestJoinResponse) GetCommunity() *CommunityDescription {
	if m != nil {
		return m.Community
	}
	return nil
}

func (m *CommunityRequestJoinResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *CommunityRequestJoinResponse) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.CommunityPermissions_Access", CommunityPermissions_Access_name, CommunityPermissions_Access_value)
	proto.RegisterType((*Grant)(nil), "protobuf.Grant")
	proto.RegisterType((*CommunityMember)(nil), "protobuf.CommunityMember")
	proto.RegisterType((*CommunityPermissions)(nil), "protobuf.CommunityPermissions")
	proto.RegisterType((*CommunityDescription)(nil), "protobuf.CommunityDescription")
	proto.RegisterMapType((map[string]*CommunityChat)(nil), "protobuf.CommunityDescription.ChatsEntry")
	proto.RegisterMapType((map[string]*CommunityMember)(nil), "protobuf.CommunityDescription.MembersEntry")
	proto.RegisterType((*CommunityChat)(nil), "protobuf.CommunityChat")
	proto.RegisterMapType((map[string]*CommunityMember)(nil), "protobuf.CommunityChat.MembersEntry")
	proto.RegisterType((*CommunityInvitation)(nil), "protobuf.CommunityInvitation")
	proto.RegisterType((*CommunityRequestJoin)(nil), "protobuf.CommunityRequestJoin")
	proto.RegisterType((*CommunityRequestJoinResponse)(nil), "protobuf.CommunityRequestJoinResponse")
}

func init() {
	proto.RegisterFile("communities.proto", fileDescriptor_f937943d74c1cd8b)
}

var fileDescriptor_f937943d74c1cd8b = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0xb9, 0x3a, 0x93, 0x5e, 0xd2, 0x6d, 0xa1, 0x6e, 0xb8, 0x28, 0x58, 0x20, 0x05, 0x21,
	0x82, 0x94, 0xbe, 0x20, 0xc4, 0xad, 0x14, 0x0b, 0x4c, 0xa9, 0xd3, 0x6e, 0x52, 0x10, 0x4f, 0x96,
	0xe3, 0x2c, 0xb0, 0x6a, 0xbc, 0x36, 0xde, 0x4d, 0xa4, 0x3c, 0xf3, 0x13, 0x3c, 0xf0, 0xc8, 0x27,
	0xf1, 0x01, 0x7c, 0x0a, 0xf2, 0x6e, 0x12, 0xbb, 0x90, 0x94, 0x4a, 0x88, 0xa7, 0x64, 0x67, 0x76,
	0xce, 0x9e, 0x39, 0x33, 0x3e, 0xb0, 0xe1, 0x87, 0x41, 0x30, 0x62, 0x54, 0x50, 0xc2, 0x5b, 0x51,
	0x1c, 0x8a, 0x10, 0xe9, 0xf2, 0xa7, 0x3f, 0xfa, 0x50, 0xdf, 0xf4, 0x3f, 0x79, 0xc2, 0xa5, 0x03,
	0xc2, 0x04, 0x15, 0x13, 0x95, 0x36, 0xc7, 0x50, 0x7c, 0x19, 0x7b, 0x4c, 0xa0, 0x9b, 0xb0, 0x32,
	0x2b, 0x9e, 0xb8, 0x74, 0x60, 0x68, 0x0d, 0xad, 0xb9, 0x82, 0xab, 0xf3, 0x98, 0x3d, 0x40, 0x57,
	0xa1, 0x12, 0x90, 0xa0, 0x4f, 0xe2, 0x24, 0x9f, 0x93, 0x79, 0x5d, 0x05, 0xec, 0x01, 0xda, 0x86,
	0xf2, 0x14, 0xdf, 0xc8, 0x37, 0xb4, 0x66, 0x05, 0x97, 0x92, 0xa3, 0x3d, 0x40, 0x5b, 0x50, 0xf4,
	0x87, 0xa1, 0x7f, 0x6a, 0x14, 0x1a, 0x5a, 0xb3, 0x80, 0xd5, 0xc1, 0xdc, 0x80, 0xf5, 0xfd, 0x19,
	0xf4, 0xa1, 0xc4, 0x30, 0x7f, 0x6a, 0xb0, 0x35, 0x8f, 0x1d, 0x91, 0x38, 0xa0, 0x9c, 0xd3, 0x90,
	0x71, 0xb4, 0x03, 0x3a, 0x61, 0xdc, 0x0d, 0xd9, 0x70, 0x22, 0x69, 0xe9, 0xb8, 0x4c, 0x18, 0xef,
	0xb0, 0xe1, 0x04, 0x19, 0x50, 0x8e, 0x62, 0x3a, 0xf6, 0x04, 0x91, 0x84, 0x74, 0x3c, 0x3b, 0xa2,
	0xc7, 0x50, 0xf2, 0x7c, 0x9f, 0x70, 0x2e, 0xe9, 0xac, 0xb5, 0x6f, 0xb7, 0x66, 0x42, 0xb4, 0x16,
	0x3d, 0xd2, 0xda, 0x93, 0x97, 0xf1, 0xb4, 0xc8, 0xec, 0x41, 0x49, 0x45, 0x10, 0x82, 0xb5, 0x13,
	0xe7, 0xc0, 0xe9, 0xbc, 0x73, 0xdc, 0xbd, 0xfd, 0x7d, 0xab, 0xdb, 0xad, 0x5d, 0x42, 0x1b, 0xb0,
	0xea, 0x74, 0xdc, 0x43, 0xeb, 0xf0, 0xb9, 0x85, 0xbb, 0xaf, 0xec, 0xa3, 0x9a, 0x86, 0x36, 0x61,
	0xdd, 0x76, 0xde, 0xda, 0xbd, 0xbd, 0x9e, 0xdd, 0x71, 0xdc, 0x8e, 0xf3, 0xe6, 0x7d, 0x2d, 0x87,
	0xd6, 0x00, 0x3a, 0x8e, 0x8b, 0xad, 0xe3, 0x13, 0xab, 0xdb, 0xab, 0xe5, 0xcd, 0x1f, 0xf9, 0x4c,
	0x8b, 0x2f, 0x08, 0xf7, 0x63, 0x1a, 0x09, 0x1a, 0xb2, 0x54, 0x24, 0x2d, 0x23, 0x12, 0xb2, 0xa0,
	0xac, 0xf4, 0xe5, 0x46, 0xae, 0x91, 0x6f, 0x56, 0xdb, 0x77, 0x17, 0x34, 0x91, 0x81, 0x69, 0x29,
	0x25, 0xb9, 0xc5, 0x44, 0x3c, 0xc1, 0xb3, 0x5a, 0xf4, 0x0c, 0xaa, 0x51, 0xda, 0xa9, 0xd4, 0xa3,
	0xda, 0xbe, 0x71, 0xbe, 0x1e, 0x38, 0x5b, 0x82, 0xda, 0xa0, 0xcf, 0xf6, 0xc6, 0x28, 0xca, 0xf2,
	0x2b, 0x99, 0x72, 0x39, 0x67, 0x95, 0xc5, 0xf3, 0x7b, 0xe8, 0x29, 0x14, 0x93, 0x0d, 0xe0, 0x46,
	0x49, 0x52, 0xbf, 0xf3, 0x17, 0xea, 0x09, 0xca, 0x94, 0xb8, 0xaa, 0xab, 0x9f, 0xc0, 0x4a, 0xb6,
	0x1f, 0x54, 0x83, 0xfc, 0x29, 0x51, 0x1b, 0x50, 0xc1, 0xc9, 0x5f, 0x74, 0x1f, 0x8a, 0x63, 0x6f,
	0x38, 0x52, 0xb3, 0xaf, 0xb6, 0x77, 0x16, 0x3c, 0xa1, 0x10, 0xb0, 0xba, 0xf7, 0x30, 0xf7, 0x40,
	0xab, 0x1f, 0x03, 0xa4, 0x6f, 0x2d, 0x00, 0xbd, 0x77, 0x16, 0x74, 0x7b, 0x01, 0x68, 0x52, 0x9f,
	0x81, 0x34, 0xbf, 0xe5, 0x60, 0xf5, 0x4c, 0x12, 0x3d, 0x49, 0x27, 0xa7, 0xc9, 0xf6, 0x6f, 0x2d,
	0x81, 0xb9, 0xd8, 0xc8, 0x72, 0xff, 0x36, 0xb2, 0xfc, 0xc5, 0x46, 0xf6, 0x9f, 0x14, 0x37, 0xbf,
	0x6a, 0xb0, 0x39, 0x4f, 0xdb, 0x6c, 0x4c, 0x85, 0x27, 0x97, 0x7e, 0x17, 0x2e, 0xa7, 0x96, 0x33,
	0x48, 0x77, 0x61, 0xea, 0x3d, 0x5b, 0xfe, 0x92, 0x2f, 0xe5, 0x63, 0x62, 0x58, 0x53, 0x03, 0x52,
	0x87, 0xe5, 0xee, 0x73, 0x1d, 0x20, 0x1a, 0xf5, 0x87, 0xd4, 0x77, 0x93, 0x4e, 0x0a, 0xb2, 0xa6,
	0xa2, 0x22, 0x07, 0x64, 0x62, 0x7e, 0xc9, 0x7a, 0x0e, 0x26, 0x9f, 0x47, 0x84, 0x8b, 0xd7, 0x21,
	0x5d, 0xf6, 0x41, 0x4e, 0x9d, 0x88, 0x79, 0x81, 0x52, 0xa0, 0x22, 0x9d, 0xc8, 0xf1, 0x02, 0xb2,
	0x9c, 0xc1, 0xef, 0xc6, 0x5a, 0xf8, 0xc3, 0x58, 0xcd, 0xef, 0x1a, 0x5c, 0x5b, 0xc4, 0x02, 0x13,
	0x1e, 0x85, 0x8c, 0x93, 0x25, 0x6c, 0x1e, 0x41, 0x65, 0x8e, 0x72, 0xce, 0x8a, 0x64, 0xd4, 0xc3,
	0x69, 0x01, 0xaa, 0x83, 0x9e, 0x78, 0x5d, 0x24, 0x88, 0x62, 0xac, 0xe3, 0xf9, 0x39, 0x15, 0xb9,
	0x90, 0x11, 0xb9, 0x5f, 0x92, 0xd8, 0xbb, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x52, 0xe8,
	0x04, 0x66, 0x06, 0x00, 0x00,
}
